[2019-11-03 10:55:48,556] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_versions 2018-11-03T01:00:00+00:00 [queued]>
[2019-11-03 10:55:48,562] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_versions 2018-11-03T01:00:00+00:00 [queued]>
[2019-11-03 10:55:48,562] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 10:55:48,562] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-03 10:55:48,562] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 10:55:48,566] {taskinstance.py:859} INFO - Executing <Task(StageToRedshiftOperator): Stage_versions> on 2018-11-03T01:00:00+00:00
[2019-11-03 10:55:48,566] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Stage_versions', '2018-11-03T01:00:00+00:00', '--job_id', '32', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpwslas9fv']
[2019-11-03 10:55:49,289] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-03 10:55:49,290] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   """)
[2019-11-03 10:55:49,380] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions [2019-11-03 10:55:49,380] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-03 10:55:49,717] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions [2019-11-03 10:55:49,717] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-03 10:55:49,730] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions [2019-11-03 10:55:49,730] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Stage_versions 2018-11-03T01:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-03 10:55:49,737] {staging_redshift.py:33} INFO - StageToRedshiftOperator for staging_versions on 2018-11-03T01:00:00+00:00
[2019-11-03 10:55:49,751] {staging_redshift.py:44} INFO - copy command 
        COPY staging_versions FROM 's3://dend-capstone-lkj/versions-1.0.0-2017-06-15.csv'
        ACCESS_KEY_ID 'AKIA2ZJJD7TPQUMASLMS'
        SECRET_ACCESS_KEY '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'
        REGION 'us-west-2'
        IGNOREHEADER 1 CSV;
        
[2019-11-03 10:55:49,754] {logging_mixin.py:95} INFO - [[34m2019-11-03 10:55:49,753[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-03 10:57:05,342] {taskinstance.py:1051} ERROR - could not connect to server: Operation timed out
	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
	TCP/IP connections on port 5439?
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
    pg_hook.run(copy_stmt)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Operation timed out
	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
	TCP/IP connections on port 5439?

[2019-11-03 10:57:05,350] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions Traceback (most recent call last):
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     args.func(args)
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     return f(*args, **kwargs)
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     _run(args, dag, ti)
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     pool=args.pool,
[2019-11-03 10:57:05,368] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     return func(*args, **kwargs)
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     result = task_copy.execute(context=context)
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     pg_hook.run(copy_stmt)
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     with closing(self.get_conn()) as conn:
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     self.conn = psycopg2.connect(**conn_args)
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions psycopg2.OperationalError: could not connect to server: Operation timed out
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions 	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions 	TCP/IP connections on port 5439?
[2019-11-03 10:57:05,369] {base_task_runner.py:115} INFO - Job 32: Subtask Stage_versions 
[2019-11-03 10:57:08,634] {logging_mixin.py:95} INFO - [[34m2019-11-03 10:57:08,634[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
