[2019-11-17 22:20:36,883] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: udacity_dag.Run_data_quality_checks 2007-10-30T00:00:00+00:00 [queued]>
[2019-11-17 22:20:36,888] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: udacity_dag.Run_data_quality_checks 2007-10-30T00:00:00+00:00 [queued]>
[2019-11-17 22:20:36,888] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 22:20:36,888] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-11-17 22:20:36,888] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 22:20:36,892] {taskinstance.py:859} INFO - Executing <Task(QualityCheckOperator): Run_data_quality_checks> on 2007-10-30T00:00:00+00:00
[2019-11-17 22:20:36,892] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'udacity_dag', 'Run_data_quality_checks', '2007-10-30T00:00:00+00:00', '--job_id', '304', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udacity_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpxpdaug7x']
[2019-11-17 22:20:37,550] {base_task_runner.py:115} INFO - Job 304: Subtask Run_data_quality_checks /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 22:20:37,551] {base_task_runner.py:115} INFO - Job 304: Subtask Run_data_quality_checks   """)
[2019-11-17 22:20:37,622] {base_task_runner.py:115} INFO - Job 304: Subtask Run_data_quality_checks [2019-11-17 22:20:37,621] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 22:20:37,907] {base_task_runner.py:115} INFO - Job 304: Subtask Run_data_quality_checks [2019-11-17 22:20:37,906] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/udacity_dag.py
[2019-11-17 22:20:37,923] {base_task_runner.py:115} INFO - Job 304: Subtask Run_data_quality_checks [2019-11-17 22:20:37,922] {cli.py:516} INFO - Running <TaskInstance: udacity_dag.Run_data_quality_checks 2007-10-30T00:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 22:20:37,929] {quality_check.py:20} INFO - QualityCheckOperator for ['staging_versions', 'staging_dependencies', 'staging_projects', 'repository_fact', 'version_dim', 'dependency_dim', 'project_dim', 'time_dim']
[2019-11-17 22:20:37,934] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:37,934[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:20:42,049] {quality_check.py:29} INFO - data quality check on staging_versions check passed with 63161735 records
[2019-11-17 22:20:42,053] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:42,053[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:20:45,050] {quality_check.py:29} INFO - data quality check on staging_dependencies check passed with 358679902 records
[2019-11-17 22:20:45,054] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:45,054[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:20:48,583] {quality_check.py:29} INFO - data quality check on staging_projects check passed with 15506757 records
[2019-11-17 22:20:48,588] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:48,588[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:20:53,550] {quality_check.py:29} INFO - data quality check on repository_fact check passed with 209385 records
[2019-11-17 22:20:53,555] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:53,555[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:20:57,988] {quality_check.py:29} INFO - data quality check on version_dim check passed with 3542 records
[2019-11-17 22:20:57,993] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:20:57,993[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:21:02,557] {quality_check.py:29} INFO - data quality check on dependency_dim check passed with 358679902 records
[2019-11-17 22:21:02,562] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:21:02,562[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:21:06,931] {quality_check.py:29} INFO - data quality check on project_dim check passed with 285 records
[2019-11-17 22:21:06,934] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:21:06,934[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 22:21:11,809] {quality_check.py:29} INFO - data quality check on time_dim check passed with 285 records
[2019-11-17 22:21:11,928] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:21:11,928[0m] {[34mlocal_task_job.py:[0m172} [33mWARNING[0m - [33mState of this instance has been externally set to [1msuccess[0m. Taking the poison pill.[0m
[2019-11-17 22:21:11,934] {helpers.py:307} INFO - Sending Signals.SIGTERM to GPID 9236
[2019-11-17 22:21:11,951] {helpers.py:285} INFO - Process psutil.Process(pid=9236, status='terminated') (9236) terminated with exit code -15
[2019-11-17 22:21:11,953] {logging_mixin.py:95} INFO - [[34m2019-11-17 22:21:11,952[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 0[0m
