[2019-11-03 14:29:22,936] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_projects 2018-11-03T05:00:00+00:00 [queued]>
[2019-11-03 14:29:22,940] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_projects 2018-11-03T05:00:00+00:00 [queued]>
[2019-11-03 14:29:22,941] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 14:29:22,941] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-03 14:29:22,941] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 14:29:22,944] {taskinstance.py:859} INFO - Executing <Task(StageToRedshiftOperator): Stage_projects> on 2018-11-03T05:00:00+00:00
[2019-11-03 14:29:22,944] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Stage_projects', '2018-11-03T05:00:00+00:00', '--job_id', '91', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpjorai1q5']
[2019-11-03 14:29:23,643] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-03 14:29:23,643] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   """)
[2019-11-03 14:29:23,732] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects [2019-11-03 14:29:23,731] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-03 14:29:24,024] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects [2019-11-03 14:29:24,023] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-03 14:29:24,037] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects [2019-11-03 14:29:24,036] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Stage_projects 2018-11-03T05:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-03 14:29:24,043] {staging_redshift.py:33} INFO - StageToRedshiftOperator for staging_projects on 2018-11-03T05:00:00+00:00
[2019-11-03 14:29:24,051] {staging_redshift.py:44} INFO - copy command 
        COPY staging_projects FROM 's3://dend-capstone-lkj/projects_with_repository_fields-1.0.0-2017-06-15.csv'
        ACCESS_KEY_ID 'AKIA2ZJJD7TPQUMASLMS'
        SECRET_ACCESS_KEY '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'
        REGION 'us-west-2'
        IGNOREHEADER 1 CSV;
        
[2019-11-03 14:29:24,053] {logging_mixin.py:95} INFO - [[34m2019-11-03 14:29:24,053[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-03 14:29:26,146] {logging_mixin.py:95} INFO - [[34m2019-11-03 14:29:26,146[0m] {[34mdbapi_hook.py:[0m171} INFO[0m - 
        COPY staging_projects FROM 's3://dend-capstone-lkj/projects_with_repository_fields-1.0.0-2017-06-15.csv'
        ACCESS_KEY_ID 'AKIA2ZJJD7TPQUMASLMS'
        SECRET_ACCESS_KEY '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'
        REGION 'us-west-2'
        IGNOREHEADER 1 CSV;
        [0m
[2019-11-03 14:29:26,897] {taskinstance.py:1051} ERROR - Load into table 'staging_projects' failed.  Check 'stl_load_errors' system table for details.
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
    pg_hook.run(copy_stmt)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
    cur.execute(s)
psycopg2.InternalError: Load into table 'staging_projects' failed.  Check 'stl_load_errors' system table for details.

[2019-11-03 14:29:26,899] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects Traceback (most recent call last):
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     args.func(args)
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     return f(*args, **kwargs)
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     _run(args, dag, ti)
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     pool=args.pool,
[2019-11-03 14:29:26,912] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     return func(*args, **kwargs)
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     result = task_copy.execute(context=context)
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     pg_hook.run(copy_stmt)
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects     cur.execute(s)
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects psycopg2.InternalError: Load into table 'staging_projects' failed.  Check 'stl_load_errors' system table for details.
[2019-11-03 14:29:26,913] {base_task_runner.py:115} INFO - Job 91: Subtask Stage_projects 
[2019-11-03 14:29:27,929] {logging_mixin.py:95} INFO - [[34m2019-11-03 14:29:27,928[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
