[2019-11-17 09:04:30,931] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-17 09:04:30,938] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-17 09:04:30,938] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 09:04:30,938] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-11-17 09:04:30,938] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 09:04:30,942] {taskinstance.py:859} INFO - Executing <Task(LoadDimensionOperator): Load_dependencies_dim_table> on 2018-11-03T16:00:00+00:00
[2019-11-17 09:04:30,943] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_dependencies_dim_table', '2018-11-03T16:00:00+00:00', '--job_id', '198', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpn2u_p14p']
[2019-11-17 09:04:31,615] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 09:04:31,616] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   """)
[2019-11-17 09:04:31,697] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table [2019-11-17 09:04:31,697] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 09:04:31,985] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table [2019-11-17 09:04:31,985] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-17 09:04:31,999] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table [2019-11-17 09:04:31,998] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 09:04:32,005] {load_dimensions.py:23} INFO - LoadDimensionOperator for dependencies
[2019-11-17 09:04:32,010] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:04:32,009[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 09:04:36,318] {load_dimensions.py:34} INFO - get 0 records from dependencies
[2019-11-17 09:04:36,323] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:04:36,322[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 09:04:39,596] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:04:39,596[0m] {[34mdbapi_hook.py:[0m171} INFO[0m - DELETE FROM dependencies[0m
[2019-11-17 09:04:40,025] {taskinstance.py:1051} ERROR - relation "dependencies" does not exist
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/load_dimensions.py", line 38, in execute
    pg_hook.run(f"DELETE FROM {self.table}")
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
    cur.execute(s)
psycopg2.ProgrammingError: relation "dependencies" does not exist

[2019-11-17 09:04:40,027] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table Traceback (most recent call last):
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     args.func(args)
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     return f(*args, **kwargs)
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     _run(args, dag, ti)
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-17 09:04:40,037] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     pool=args.pool,
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     return func(*args, **kwargs)
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     result = task_copy.execute(context=context)
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/airflow/plugins/operators/load_dimensions.py", line 38, in execute
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     pg_hook.run(f"DELETE FROM {self.table}")
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table     cur.execute(s)
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table psycopg2.ProgrammingError: relation "dependencies" does not exist
[2019-11-17 09:04:40,038] {base_task_runner.py:115} INFO - Job 198: Subtask Load_dependencies_dim_table 
[2019-11-17 09:04:40,932] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:04:40,931[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
