[2019-11-17 09:15:49,811] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-17 09:15:49,816] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-17 09:15:49,816] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 09:15:49,816] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-17 09:15:49,816] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 09:15:49,821] {taskinstance.py:859} INFO - Executing <Task(LoadDimensionOperator): Load_dependencies_dim_table> on 2018-11-03T16:00:00+00:00
[2019-11-17 09:15:49,821] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_dependencies_dim_table', '2018-11-03T16:00:00+00:00', '--job_id', '210', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpatl6tnsx']
[2019-11-17 09:15:50,574] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 09:15:50,575] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   """)
[2019-11-17 09:15:50,661] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table [2019-11-17 09:15:50,660] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 09:15:50,949] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table [2019-11-17 09:15:50,949] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-17 09:15:50,963] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table [2019-11-17 09:15:50,962] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_dependencies_dim_table 2018-11-03T16:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 09:15:50,969] {load_dimensions.py:23} INFO - LoadDimensionOperator for dependencies
[2019-11-17 09:15:50,974] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:15:50,974[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 09:15:52,973] {load_dimensions.py:34} INFO - get 0 records from dependencies
[2019-11-17 09:15:52,976] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:15:52,976[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 09:15:54,488] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:15:54,488[0m] {[34mdbapi_hook.py:[0m171} INFO[0m - DELETE FROM dependencies[0m
[2019-11-17 09:15:54,919] {taskinstance.py:1051} ERROR - relation "dependencies" does not exist
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/load_dimensions.py", line 38, in execute
    pg_hook.run(f"DELETE FROM {self.table}")
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
    cur.execute(s)
psycopg2.ProgrammingError: relation "dependencies" does not exist

[2019-11-17 09:15:54,922] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-17 09:15:54,932] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table Traceback (most recent call last):
[2019-11-17 09:15:54,932] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-17 09:15:54,932] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     args.func(args)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     return f(*args, **kwargs)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     _run(args, dag, ti)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     pool=args.pool,
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     return func(*args, **kwargs)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     result = task_copy.execute(context=context)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/airflow/plugins/operators/load_dimensions.py", line 38, in execute
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     pg_hook.run(f"DELETE FROM {self.table}")
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table     cur.execute(s)
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table psycopg2.ProgrammingError: relation "dependencies" does not exist
[2019-11-17 09:15:54,933] {base_task_runner.py:115} INFO - Job 210: Subtask Load_dependencies_dim_table 
[2019-11-17 09:15:59,819] {logging_mixin.py:95} INFO - [[34m2019-11-17 09:15:59,819[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
