[2019-11-12 14:06:28,843] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [queued]>
[2019-11-12 14:06:28,850] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [queued]>
[2019-11-12 14:06:28,850] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-12 14:06:28,850] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-11-12 14:06:28,850] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-12 14:06:28,856] {taskinstance.py:859} INFO - Executing <Task(LoadFactOperator): Load_repositories_fact_table> on 2018-11-03T14:00:00+00:00
[2019-11-12 14:06:28,856] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_repositories_fact_table', '2018-11-03T14:00:00+00:00', '--job_id', '174', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpoj81mxyw']
[2019-11-12 14:06:29,608] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-12 14:06:29,609] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   """)
[2019-11-12 14:06:29,691] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table [2019-11-12 14:06:29,690] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-12 14:06:30,012] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table [2019-11-12 14:06:30,012] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-12 14:06:30,027] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table [2019-11-12 14:06:30,027] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-12 14:06:30,034] {load_facts.py:21} INFO - LoadFactOperator for repositories
[2019-11-12 14:06:30,034] {taskinstance.py:1051} ERROR - type object 'SqlQueries' has no attribute 'repository_table_insert'
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 25, in execute
    records = pg_hook.get_records(SqlQueries.repository_table_insert)
AttributeError: type object 'SqlQueries' has no attribute 'repository_table_insert'
[2019-11-12 14:06:30,037] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-11-12 14:06:30,048] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table Traceback (most recent call last):
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     args.func(args)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     return f(*args, **kwargs)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     _run(args, dag, ti)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     pool=args.pool,
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     return func(*args, **kwargs)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     result = task_copy.execute(context=context)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table   File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 25, in execute
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table     records = pg_hook.get_records(SqlQueries.repository_table_insert)
[2019-11-12 14:06:30,052] {base_task_runner.py:115} INFO - Job 174: Subtask Load_repositories_fact_table AttributeError: type object 'SqlQueries' has no attribute 'repository_table_insert'
[2019-11-12 14:06:33,844] {logging_mixin.py:95} INFO - [[34m2019-11-12 14:06:33,844[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
