[2019-11-12 14:23:02,731] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [queued]>
[2019-11-12 14:23:02,736] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [queued]>
[2019-11-12 14:23:02,736] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-12 14:23:02,736] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-12 14:23:02,736] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-12 14:23:02,740] {taskinstance.py:859} INFO - Executing <Task(LoadFactOperator): Load_repositories_fact_table> on 2018-11-03T14:00:00+00:00
[2019-11-12 14:23:02,740] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_repositories_fact_table', '2018-11-03T14:00:00+00:00', '--job_id', '177', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpbselp2et']
[2019-11-12 14:23:03,446] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-12 14:23:03,447] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   """)
[2019-11-12 14:23:03,540] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table [2019-11-12 14:23:03,540] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-12 14:23:03,834] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table [2019-11-12 14:23:03,833] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-12 14:23:03,848] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table [2019-11-12 14:23:03,848] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T14:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-12 14:23:03,855] {load_facts.py:21} INFO - LoadFactOperator for repositories
[2019-11-12 14:23:03,862] {logging_mixin.py:95} INFO - [[34m2019-11-12 14:23:03,862[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-12 14:30:54,584] {taskinstance.py:1051} ERROR - column "github" does not exist in sp, sv, unnamed_join, sd, unnamed_join, ss, unnamed_join
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 25, in execute
    records = pg_hook.get_records(SqlQueries.repository_table_select)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 117, in get_records
    cur.execute(sql)
psycopg2.ProgrammingError: column "github" does not exist in sp, sv, unnamed_join, sd, unnamed_join, ss, unnamed_join

[2019-11-12 14:30:54,587] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table Traceback (most recent call last):
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     args.func(args)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     return f(*args, **kwargs)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     _run(args, dag, ti)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     pool=args.pool,
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     return func(*args, **kwargs)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     result = task_copy.execute(context=context)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 25, in execute
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     records = pg_hook.get_records(SqlQueries.repository_table_select)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 117, in get_records
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table     cur.execute(sql)
[2019-11-12 14:30:54,598] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table psycopg2.ProgrammingError: column "github" does not exist in sp, sv, unnamed_join, sd, unnamed_join, ss, unnamed_join
[2019-11-12 14:30:54,599] {base_task_runner.py:115} INFO - Job 177: Subtask Load_repositories_fact_table 
[2019-11-12 14:30:58,354] {logging_mixin.py:95} INFO - [[34m2019-11-12 14:30:58,354[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
